### ISSUE TITLE
Add documentation.

### ISSUE THREAD

**Issue by waynemwashuma** [Oats-i/Oats-i#3]
Nice job to the devs but i have an issue with the project: **Documentation**.

I cannot find a way how to build anything with the framework,what can i build with it, what platform it is for(Web,Android) or even a site for this framework.

The only docs are for how to start up a dev server and the rest is up to you.

I suggest adding tutorials, making a few demos with the framework and giving more detail about this framework.

**Comment by waynemwashuma** [comment]
API documentation can also be included in the docs.

**Comment by Oats-i** [comment]
Hi Wayne,

Thanks for the compliments 🙏. I appreciate that you love and are interested in the work so far. Official documentation is on the works, but there are nice tutorials to follow over at dev.to (https://dev.to/oatsi) and YouTube (https://www.youtube.com/@Oatsi). I'm adding more tutorials with time, preferably video tutorials, since I find those easier to do and explain compared to written articles. You can follow us in both channels to stay up-to-date.

Once the official site and documentation drops, I'll update that here as well. I'll close this ticket the day the official documentation will be done. For now, I hope the videos and articles will be extremely helpful.
